docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Intro: intro.md
    - Reference:
        - "Memory Manager": memory-manager.md
        - "Memory Objects": memory-objects.md
site_name: laminas-memory
site_description: laminas-memory
repo_url: 'https://github.com/laminas/laminas-memory'
